### ISSUE TITLE
Add MinIO delete bug workaround

### ISSUE THREAD

**Issue by Foxcapades** [VEuPathDB/lib-s34k-minio#13]
Ref: https://github.com/VEuPathDB/lib-s3-workspace/issues/9
Ref: https://github.com/VEuPathDB/lib-s3-workspace/issues/6

MinIO has a bug when site replication is enabled that causes objects to be available through the API after a success response from a DELETE request.

The workaround that was implemented in s3-workspaces was to poll MinIO until the object is no longer available.  That fix should be in this library as the lowest level wrapper we control around the MinIO client.

However, introducing blocking code into the library requires finally fixing the S34K API to include suspend modifiers on IO based methods (most of the API) which will be a big change.

**Comment by Foxcapades** [comment]
```
2025-06-20 10:56:01.616 [rid:1RRQ9][jid:][p:][tid:180] ERROR ErrorMapper:67 - Caught Exception: 
 org.veupathdb.lib.s3.s34k.errors.S34KError: Failed to test if object '6f8ba5f10d7189700724a9a04b958e25/.expired' exists in Bucket{ name='eda-compute-prod' }
        at org.veupathdb.lib.s3.s34k.minio.operations.Simple_object_opsKt.ObjectExists(simple-object-ops.kt:153) ~[service.jar:3.0.0]
        at org.veupathdb.lib.s3.s34k.minio.MObject.exists(MObject.kt:45) ~[service.jar:3.0.0]
        at org.veupathdb.lib.s3.s34k.core.objects.AbstractS3Object.exists(AbstractS3Object.kt:49) ~[service.jar:3.0.0]
        at org.veupathdb.lib.compute.platform.intern.s3.S3.minioObjectDeleteHack(S3.kt:170) ~[service.jar:3.0.0]
        at org.veupathdb.lib.compute.platform.intern.s3.S3.wipeWorkspace(S3.kt:155) ~[service.jar:3.0.0]
        at org.veupathdb.lib.compute.platform.intern.s3.S3.deleteWorkspace(S3.kt:133) ~[service.jar:3.0.0]
        at org.veupathdb.lib.compute.platform.AsyncPlatform.submitJob(AsyncPlatform.kt:174) ~[service.jar:3.0.0]
        at org.veupathdb.service.eda.compute.EDACompute.getOrSubmitComputeJob(EDACompute.kt:122) ~[service.jar:3.0.0]
        at org.veupathdb.service.eda.compute.controller.ComputeController.submitJob(ComputeController.java:257) ~[service.jar:3.0.0]
        at org.veupathdb.service.eda.compute.controller.ComputeController.postComputesAlphadiv(ComputeController.java:103) ~[service.jar:3.0.0]
        at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
        at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52) ~[service.jar:3.0.0]
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:146) ~[service.jar:3.0.0]
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:189) ~[service.jar:3.0.0]
        at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:176) ~[service.jar:3.0.0]
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:93) ~[service.jar:3.0.0]
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:478) ~[service.jar:3.0.0]
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:400) ~[service.jar:3.0.0]
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:81) ~[service.jar:3.0.0]
        at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:274) ~[service.jar:3.0.0]
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248) ~[service.jar:3.0.0]
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244) ~[service.jar:3.0.0]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:292) ~[service.jar:3.0.0]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:274) ~[service.jar:3.0.0]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:244) ~[service.jar:3.0.0]
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:266) ~[service.jar:3.0.0]
        at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:253) ~[service.jar:3.0.0]
        at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:696) ~[service.jar:3.0.0]
        at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:367) ~[service.jar:3.0.0]
        at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:190) ~[service.jar:3.0.0]
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:535) ~[service.jar:3.0.0]
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:515) ~[service.jar:3.0.0]
        at java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: io.minio.errors.ServerException: server failed with HTTP status code 500
        at io.minio.S3Base$1.onResponse(S3Base.java:753) ~[service.jar:3.0.0]
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519) ~[service.jar:3.0.0]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        ... 1 more
```
